### ISSUE TITLE
add support for extracting formulas or formulas' computed value

### ISSUE THREAD

**Issue by Roms1383** [masklinn/xls2txt#1]
Hi and thanks for this utility, it's very convenient I just tried it out.
I'm not sure if it's possible, but could formulas themselves _or_ formulas computed displayed value could be exported as well ?

**Comment by masklinn** [comment]
Heya,

Well this is just a thin layer between calamine and csv, and calamine doesn't include a formula evaluator, so that's not really an option (yet anyway).

Currently xls2txt will display the "preview" if the spreadsheet embeds one, I could probably add a pair of options for formulas:
- show the formula if a formula cell is empty (doesn't have a value / preview)
- show the formula always (regardless of the cell's value)

Then longer term adding a dependency on an other crate might be an option (e.g. there's one called xlformula_engine which apparently aims to do that, might be worth looking at), that would be one more evaluation mode.

**Comment by Roms1383** [comment]
Well, `calamine` does indeed support extracting formulas now, I gave it a try yesterday and it seemed to work. Haven't try if it can write them to the output e.g. txt yet though. As far as I could tell your crate didn't extract the formulas "preview" apparently, at least when running `xls2csv` if I remember correctly.

**Comment by Roms1383** [comment]
a bit more context :
- formulas are apparently supported on `calamine` 0.19.1 : see [worksheet_formula](https://docs.rs/calamine/0.19.1/calamine/struct.Xls.html#method.worksheet_formula)
  I indeed can log the formulas correctly
- tested on MacOS M1 Pro (Monterey 12.4)

**Comment by masklinn** [comment]
> Well, `calamine` does indeed support extracting formulas now, I gave it a try yesterday and it seemed to work. Haven't try if it can write them to the output e.g. txt yet though. As far as I could tell your crate didn't extract the formulas "preview" apparently, at least when running `xls2csv` if I remember correctly.

By "preview" I meant that the spreadsheet program can store data in the formula cell (at least in XLSX), which allows naïve viewers to see the values the spreadsheet stored even if they can't evaluate the formulas themselves.

For instance I exported these two spreadsheets with Numbers from the same content: 
- [formulas.xls](https://github.com/masklinn/xls2txt/files/9880765/formulas.xls)
- [formulas.xlsx](https://github.com/masklinn/xls2txt/files/9880767/formulas.xlsx)
The third column is the sum of the first two, the xls shows no content:
```
> xls2txt formulas.xls
Table 1			
	Thing	Thing2	Thing3
A	1	5947	
B	2	49328	
C	3	98347	
C	5	48643	
E	4	126753	
```
while the xlsx does show content:
```
> xls2txt formulas.xlsx
Table 1			
	Thing	Thing2	Thing3
A	1	5947	5948
B	2	49328	49330
C	3	98347	98350
C	5	48643	48648
E	4	126753	126757
```
What you're talking about is extracting the formulas themselves, then merging them with the data (calamine extracts the two as unrelated ranges).

Which again I'm open to, but will require a bit more work, and an additional option to control what gets displayed as as you can see above the current behaviour is not a no-op on formula cells.

**Comment by masklinn** [comment]
@Roms1383 see #2 for an initial draft of displaying formulas if you want to play with it. Uses a new option (so the current default doesn't change, as I think displaying formulas by default would be unclear / confusing).

**Comment by Roms1383** [comment]
Ok I'm little tight on time but I'll try to give it a check. Thanks for your reply it's interesting indeed :)

**Comment by Roms1383** [comment]
> For instance I exported these two spreadsheets with Numbers from the same content (...)

I gave a very quick try at #2 indeed looks great already:
my results exactly match yours, also tested with different `.xls` and `.xlsx` samples.
